## Splitting dataset


import os
import numpy as np
from PIL import Image

### Splitting data

def load_data(train_folder, test_folder):
    def load_images_from_folder(folder):
        images = []
        labels = []
        for label in os.listdir(folder):
            label_path = os.path.join(folder, label)
            if os.path.isdir(label_path):
                i=1
                for filename in os.listdir(label_path):
                    img_path = os.path.join(label_path, filename)
                    img = Image.open(img_path)
                    img = img.resize((128, 128))
                    img = img.convert("L")
                    img_array = np.array(img)
                    images.append(img_array)
                    labels.append(label)
                    #print(img.size)
                    #print("Label path: ", label_path, "-",i)
                    i=i+1
        return np.array(images), np.array(labels)

    X_train, y_train = load_images_from_folder(train_folder)
    X_test, y_test = load_images_from_folder(test_folder)

    return (X_train, y_train), (X_test, y_test)

# Specify the paths to your train and test folders
train_folder = r'D:\PCOS_Challenge\train'
val_folder = r'D:\PCOS_Challenge\validate'

# Load the custom MNIST dataset
(X_train, y_train), (X_test, y_test) = load_data(train_folder, val_folder)


# Print the shape of the training and testing datasets
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)


X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

# normalizing the data to help with the training
X_train /= 255
X_test /= 255

In [129]:
import os
import numpy as np
from PIL import Image
from sklearn.model_selection import train_test_split

def load_data(image_folder, validation_size=0.3, test_size=0.1):
    def load_images_from_folder(folder):
        images = []
        labels = []
        for label in os.listdir(folder):
            label_path = os.path.join(folder, label)
            if os.path.isdir(label_path):
                i = 1
                for filename in os.listdir(label_path):
                    img_path = os.path.join(label_path, filename)
                    img = Image.open(img_path)
                    img = img.resize((128, 128))
                    img = img.convert("L")
                    img_array = np.array(img)
                    images.append(img_array)
                    labels.append(label)
                    i = i + 1
        return np.array(images), np.array(labels)

    # Load data for training and validation
    X_train, X_temp, y_train, y_temp = train_test_split(*load_images_from_folder(image_folder),
                                                        test_size=validation_size,
                                                        random_state=42, shuffle = True)
    
    # Further split the temporary data into validation and test sets
    X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=test_size,
                                                    random_state=42, shuffle = True)

    return (X_train, y_train), (X_val, y_val), (X_test, y_test)

# Specify the paths to your train, validation, and test folders
train_folder = r'D:\PCOS_Challenge\train'
val_folder = r'D:\PCOS_Challenge\validate'
test_folder = r'D:\PCOS_Challenge\test'

image_folder = r'D:\PCOS_Challenge\Newer_Version\original_data'

# Load the custom dataset with train, validation, and test sets
(X_train, y_train), (X_val, y_val), (X_test, y_test) = load_data(image_folder)

# Print the shape of the training, validation, and testing datasets
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_val shape:", X_val.shape)
print("y_val shape:", y_val.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

X_train = X_train.astype('float32')
X_val = X_val.astype('float32')
X_test = X_test.astype('float32')

# Normalizing the data to help with the training
X_train /= 255
X_val /= 255
X_test /= 255


X_train shape: (2240, 128, 128)
y_train shape: (2240,)
X_val shape: (864, 128, 128)
y_val shape: (864,)
X_test shape: (96, 128, 128)
y_test shape: (96,)


In [130]:
y_train 

array(['unhealthy', 'unhealthy', 'unhealthy', ..., 'unhealthy', 'healthy',
       'unhealthy'], dtype='<U9')

In [131]:
y_val   

array(['unhealthy', 'unhealthy', 'unhealthy', 'unhealthy', 'unhealthy',
       'unhealthy', 'unhealthy', 'unhealthy', 'healthy', 'unhealthy',
       'healthy', 'unhealthy', 'healthy', 'unhealthy', 'unhealthy',
       'healthy', 'healthy', 'unhealthy', 'unhealthy', 'unhealthy',
       'unhealthy', 'unhealthy', 'unhealthy', 'unhealthy', 'unhealthy',
       'unhealthy', 'healthy', 'unhealthy', 'healthy', 'healthy',
       'healthy', 'unhealthy', 'unhealthy', 'unhealthy', 'unhealthy',
       'unhealthy', 'unhealthy', 'unhealthy', 'healthy', 'healthy',
       'unhealthy', 'unhealthy', 'unhealthy', 'unhealthy', 'unhealthy',
       'unhealthy', 'healthy', 'healthy', 'unhealthy', 'healthy',
       'unhealthy', 'healthy', 'healthy', 'healthy', 'healthy', 'healthy',
       'unhealthy', 'unhealthy', 'unhealthy', 'unhealthy', 'unhealthy',
       'unhealthy', 'unhealthy', 'unhealthy', 'unhealthy', 'healthy',
       'healthy', 'healthy', 'healthy', 'unhealthy', 'unhealthy',
       'unhealthy', 'unhe

In [132]:
y_test 

array(['unhealthy', 'unhealthy', 'healthy', 'unhealthy', 'healthy',
       'unhealthy', 'unhealthy', 'healthy', 'unhealthy', 'unhealthy',
       'unhealthy', 'unhealthy', 'healthy', 'unhealthy', 'unhealthy',
       'unhealthy', 'unhealthy', 'unhealthy', 'unhealthy', 'unhealthy',
       'healthy', 'healthy', 'unhealthy', 'unhealthy', 'healthy',
       'unhealthy', 'unhealthy', 'unhealthy', 'unhealthy', 'healthy',
       'unhealthy', 'unhealthy', 'unhealthy', 'unhealthy', 'unhealthy',
       'unhealthy', 'unhealthy', 'healthy', 'unhealthy', 'healthy',
       'unhealthy', 'healthy', 'unhealthy', 'unhealthy', 'healthy',
       'unhealthy', 'unhealthy', 'unhealthy', 'unhealthy', 'unhealthy',
       'unhealthy', 'unhealthy', 'healthy', 'unhealthy', 'healthy',
       'unhealthy', 'healthy', 'unhealthy', 'healthy', 'healthy',
       'healthy', 'unhealthy', 'healthy', 'healthy', 'healthy',
       'unhealthy', 'unhealthy', 'healthy', 'unhealthy', 'unhealthy',
       'unhealthy', 'unhealthy', 'un

In [133]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
label_encoder.fit(["healthy", "unhealthy"])
list(label_encoder.classes_)


['healthy', 'unhealthy']

In [134]:
y_train_encoded = label_encoder.transform(y_train)
y_val_encoded = label_encoder.transform(y_val)

In [136]:
y_train_encoded[-2]

0

In [137]:
from keras.utils import to_categorical

y_train_one_hot = to_categorical(y_train_encoded)
y_val_one_hot = to_categorical(y_val_encoded)

In [138]:
y_train_one_hot

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [1., 0.],
       [0., 1.]], dtype=float32)

In [139]:
y_val_one_hot

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [1., 0.]], dtype=float32)

## ID_Net Model

In [140]:
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow.keras import regularizers
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Input, Flatten, Dense, Dropout, BatchNormalization, Add, Activation
from tensorflow.keras.layers import Conv2D, MaxPooling2D, AveragePooling2D, ZeroPadding2D
from tensorflow.keras.layers import Concatenate
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.optimizers import Adam, SGD

In [141]:
int(X_train.shape[0]/2)

1120

In [142]:
CLASS_NUM = 2
BATCH_SIZE = 2
EPOCH_STEPS = int(X_train.shape[0]/BATCH_SIZE)
IMAGE_SHAPE = (128, 128, 1)

In [143]:
# create model

def resnet(x, filters):

    X_shortcut = x
     # 1x1
    path1 = Conv2D(filters=filters[0], kernel_size=(1,1), strides=1, padding='same', activation='relu')(x)
    path1 = BatchNormalization()(path1)
    path1 = Activation('relu')(path1)
    
    # 1x1->3x3
    path2 = Conv2D(filters=filters[1][0], kernel_size=(1,1), strides=1, padding='same', activation='relu')(path1)
    path2 = Conv2D(filters=filters[1][1], kernel_size=(3,3), strides=1, padding='same', activation='relu')(path2)
    path2 = BatchNormalization()(path2)
    path2 = Activation('relu')(path2)
    
    # 1x1->5x5
    path3 = Conv2D(filters=filters[2][0], kernel_size=(1,1), strides=1, padding='same', activation='relu')(path2)
    path3 = Conv2D(filters=filters[2][1], kernel_size=(5,5), strides=1, padding='same', activation='relu')(path3)
    path3 = BatchNormalization()(path3)
    path3 = Activation('relu')(path3)
    
    # 3x3->1x1
    path4 = MaxPooling2D(pool_size=(3,3), strides=1, padding='same')(path3)
    path4 = Conv2D(filters=filters[3], kernel_size=(1,1), strides=1, padding='same', activation='relu')(path4)

    X_shortcut = Conv2D(filters=filters[3], kernel_size=(1,1), strides=1, padding='same')(X_shortcut)
    # Add shortcut value to main path
    X = Add()([X_shortcut, path4])
    X = Activation('relu')(path4)
    
    return X

    


def auxiliary(x, name=None):
    layer = AveragePooling2D(pool_size=(5,5), strides=3, padding='valid')(x)
    layer = Conv2D(filters=128, kernel_size=(1,1), strides=1, padding='same', activation='relu')(layer)
    layer = Flatten()(layer)
    layer = Dense(units=256, activation='relu')(layer)
    layer = Dropout(0.4)(layer)
    layer = Dense(units=CLASS_NUM, activation='softmax', name=name)(layer)
    
    
    return layer


def googlenet():
    layer_in = Input(shape=IMAGE_SHAPE)
    #layer_in = resnet_50.input
    
    # stage-1
    layer = Conv2D(filters=64, kernel_size=(7,7), strides=2, padding='same', activation='relu')(layer_in)
    layer = MaxPooling2D(pool_size=(3,3), strides=2, padding='same')(layer)
    layer = BatchNormalization()(layer)

    # stage-2
    layer = Conv2D(filters=64, kernel_size=(1,1), strides=1, padding='same', activation='relu')(layer)
    layer = Conv2D(filters=192, kernel_size=(3,3), strides=1, padding='same', activation='relu')(layer)
    layer = BatchNormalization()(layer)
    layer = MaxPooling2D(pool_size=(3,3), strides=2, padding='same')(layer)

    # stage-3
    layer = Conv2D(filters=96, kernel_size=(3,3), strides=1, padding='same', activation='relu')(layer)
    #layer = inception(layer, [ 64,  (96,128), (16,32), 32]) #3a
    #layer = inception(layer, [128, (128,192), (32,96), 64]) #3b
    layer = resnet(layer, [ 64,  (96,128), (16,32), 32])
    layer = resnet(layer, filters = [128, (128,192), (32,96), 64])
    layer = MaxPooling2D(pool_size=(3,3), strides=2, padding='same')(layer)
    
    # stage-4
    layer = Conv2D(filters=96, kernel_size=(3,3), strides=1, padding='same', activation='relu')(layer)
    #layer = inception(layer, [192,  (96,208),  (16,48),  64]) #4a
    layer = resnet(layer, [192,  (96,208),  (16,48),  64]) #4a
    aux1  = auxiliary(layer, name='aux1')
    #layer = inception(layer, [160, (112,224),  (24,64),  64]) #4b
    #layer = inception(layer, [128, (128,256),  (24,64),  64]) #4c
    #layer = inception(layer, [112, (144,288),  (32,64),  64]) #4d
    layer = Conv2D(filters=112, kernel_size=(3,3), strides=1, padding='same', activation='relu')(layer)
    layer = resnet(layer, [160, (112,224),  (24,64),  64]) #4b
    layer = resnet(layer, [128, (128,256),  (24,64),  64]) #4c
    layer = resnet(layer, [112, (144,288),  (32,64),  64]) #4d
    aux2  = auxiliary(layer, name='aux2')
    #layer = inception(layer, [256, (160,320), (32,128), 128]) #4e
    #layer = Conv2D(filters=320, kernel_size=(3,3), strides=1, padding='same', activation='relu')(layer)
    layer = resnet(layer, [256, (160,320), (32,128), 128])
    layer = MaxPooling2D(pool_size=(3,3), strides=2, padding='same')(layer)
    
    layer = AveragePooling2D(pool_size=(7,7), strides=(1, 1), padding='same')(layer)

    #layer = resnet_50.output
    
    # stage-6
    layer = Flatten()(layer)
    layer = Dropout(0.4)(layer)
    layer = Dense(units=256, activation='linear')(layer)
    main = Dense(units=CLASS_NUM, activation='softmax', name='main')(layer)
    
    model = Model(inputs=layer_in, outputs=[main, aux1, aux2])
    
    return model



## Model Summery

In [144]:
# train model
model = googlenet()
model.summary()

Model: "model_4"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_5 (InputLayer)        [(None, 128, 128, 1)]        0         []                            
                                                                                                  
 conv2d_228 (Conv2D)         (None, 64, 64, 64)           3200      ['input_5[0][0]']             
                                                                                                  
 max_pooling2d_44 (MaxPooli  (None, 32, 32, 64)           0         ['conv2d_228[0][0]']          
 ng2D)                                                                                            
                                                                                                  
 batch_normalization_92 (Ba  (None, 32, 32, 64)           256       ['max_pooling2d_44[0][0]

## Train the model

In [ ]:
optimizer = ['Adam', 'SGD', 'Adam', 'SGD']
epochs = [50,50,50,50]
history_all = {}

for i in range(len(optimizer)):
    print('Usnig optimizer: ' + optimizer[i] + ', Epoch: ' + str(epochs[i]))
    
    model.compile(loss='categorical_crossentropy', 
                  loss_weights={'main': 1.0,'aux1': 0.3, 'aux2': 0.3},
                  optimizer=optimizer[i], metrics=['accuracy'])
    
    train_history = model.fit(X_train, 
                              y_train_one_hot, 
                              steps_per_epoch=EPOCH_STEPS, 
                              epochs=epochs[i], shuffle=True, 
                              validation_data=(X_val, y_val_one_hot))
    
    # save history    
    if len(history_all) == 0:
        history_all = {key: [] for key in train_history.history}
    
    for key in history_all:
        history_all[key].extend(train_history.history[key])

Usnig optimizer: Adam, Epoch: 50
Epoch 1/50
1120/1120 [==============================] - 66s 51ms/step - loss: 1.2843 - main_loss: 0.9085 - aux1_loss: 0.6190 - aux2_loss: 0.6338 - main_accuracy: 0.7188 - aux1_accuracy: 0.7183 - aux2_accuracy: 0.7152 - val_loss: 3.1691 - val_main_loss: 0.6158 - val_aux1_loss: 1.0089 - val_aux2_loss: 7.5023 - val_main_accuracy: 0.6956 - val_aux1_accuracy: 0.6956 - val_aux2_accuracy: 0.6956
Epoch 2/50
1120/1120 [==============================] - 55s 49ms/step - loss: 0.9486 - main_loss: 0.5915 - aux1_loss: 0.5954 - aux2_loss: 0.5950 - main_accuracy: 0.7241 - aux1_accuracy: 0.7263 - aux2_accuracy: 0.7272 - val_loss: 1.5309 - val_main_loss: 0.6193 - val_aux1_loss: 0.7117 - val_aux2_loss: 2.3271 - val_main_accuracy: 0.6956 - val_aux1_accuracy: 0.6956 - val_aux2_accuracy: 0.6956
Epoch 3/50
1120/1120 [==============================] - 54s 49ms/step - loss: 0.9490 - main_loss: 0.5935 - aux1_loss: 0.5894 - aux2_loss: 0.5956 - main_accuracy: 0.7263 - aux1_accurac

In [ ]:
MODEL_NAME = r"D:\PCOS_Challenge\Test_model"
model.save(MODEL_NAME)

In [ ]:
# show train history
def show_train_history(history, xlabel, ylabel, train):
    for item in train:
        plt.plot(history[item])
    plt.title('Train History')
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.legend(train, loc='upper left')
    plt.show()

show_train_history(history_all, 'Epoch', 'Accuracy', ('main_accuracy', 'aux1_accuracy', 'aux2_accuracy'))
show_train_history(history_all, 'Epoch', 'Loss', ('main_loss', 'aux1_loss', 'aux2_loss'))

In [ ]:

# Get model predictions
predictions = model.predict(X_test)

# If your predictions are one-hot encoded, convert them to integer labels
predicted_labels = np.argmax(predictions[1], axis=1)

predicted_labels

In [ ]:
predictions

In [ ]:
from sklearn.metrics import confusion_matrix

y_test_encoded = label_encoder.transform(y_test)
y_test_one_hot = to_categorical(y_test_encoded)

# Assuming y_test_one_hot is a one-hot encoded array
y_true = np.argmax(y_test_one_hot, axis=1)
# Compute the confusion matrix
cm = confusion_matrix(y_true, predicted_labels)

print(cm)

## Testing the model

In [1]:
from tensorflow.keras.models import load_model

MODEL_NAME = r"D:\PCOS_Challenge\Test_model"
model = load_model(MODEL_NAME)

In [3]:

## Testing


import os
import numpy as np
from PIL import Image

test_path = r"D:\PCOS_Challenge\Test data\images"
images =[]
image_path =[]
for finename in os.listdir(test_path):
    img_path = os.path.join(test_path, finename)
    image_path.append(img_path)
    img = Image.open(img_path)
    img = img.resize((128, 128))
    img = img.convert("L")
    img_array = np.array(img)
    images.append(img_array)
    
test_images = np.array(images)

In [4]:
test_images

array([[[  2,   3,   3, ...,   3,   3,   1],
        [  1,   0,  11, ...,  26,  16,   6],
        [  4,   2,  24, ...,  41,  20,  13],
        ...,
        [  1,   1,   1, ...,   3,   3,   3],
        [  1,   1,   1, ...,   3,   3,   3],
        [  1,   1,   1, ...,   3,   3,   3]],

       [[  1,   1,   1, ..., 205, 179,  97],
        [  1,   1,   1, ..., 134,  72,  19],
        [  1,   1,   1, ...,  18,  11,   6],
        ...,
        [  1,   1,   1, ...,   1,   1,   1],
        [  1,   1,   1, ...,   1,   1,   1],
        [  1,   1,   1, ...,   1,   1,   1]],

       [[  7,   7,   7, ...,   7,   7,   7],
        [  7,   7,   7, ...,   7,   7,   7],
        [  7,   7,   7, ...,   7,   7,   7],
        ...,
        [  7,   7,   7, ...,   5,   8,   8],
        [  7,   7,   7, ...,  10,  14,   9],
        [  7,   7,   7, ...,   7,  10,   6]],

       ...,

       [[ 48,  48,  49, ...,  35,  34,  31],
        [ 48,  47,  48, ...,  35,  34,  31],
        [ 47,  46,  48, ...,  35,  34,  31

### Prediction

In [5]:

test_pred = model.predict(test_images)

46/46 [==============================] - 4s 70ms/step


In [6]:
test_pred[0]

array([[0.28200927, 0.7179907 ],
       [0.28200927, 0.7179907 ],
       [0.28200927, 0.7179907 ],
       ...,
       [0.28200927, 0.7179907 ],
       [0.28200927, 0.7179907 ],
       [0.28200927, 0.7179907 ]], dtype=float32)

In [7]:

test_predicted_labels = np.argmax(test_pred[0], axis=1)

test_predicted_labels

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [11]:
img_path =[]
for path in image_path:
    p = path.split('\\')
    #print(p[-1])
    img_path.append(p[-1])
    #break

In [12]:
img_path

['image10000.jpg',
 'image10001.jpg',
 'image10002.jpg',
 'image10003.jpg',
 'image10004.jpg',
 'image10005.jpg',
 'image10006.jpg',
 'image10007.jpg',
 'image10008.jpg',
 'image10009.jpg',
 'image10010.jpg',
 'image10011.jpg',
 'image10012.jpg',
 'image10013.jpg',
 'image10014.jpg',
 'image10015.jpg',
 'image10016.jpg',
 'image10017.jpg',
 'image10018.jpg',
 'image10019.jpg',
 'image10020.jpg',
 'image10021.jpg',
 'image10022.jpg',
 'image10023.jpg',
 'image10024.jpg',
 'image10025.jpg',
 'image10026.jpg',
 'image10027.jpg',
 'image10028.jpg',
 'image10029.jpg',
 'image10030.jpg',
 'image10031.jpg',
 'image10032.jpg',
 'image10033.jpg',
 'image10034.jpg',
 'image10035.jpg',
 'image10036.jpg',
 'image10037.jpg',
 'image10038.jpg',
 'image10039.jpg',
 'image10040.jpg',
 'image10041.jpg',
 'image10042.jpg',
 'image10043.jpg',
 'image10044.jpg',
 'image10045.jpg',
 'image10046.jpg',
 'image10047.jpg',
 'image10048.jpg',
 'image10049.jpg',
 'image10050.jpg',
 'image10051.jpg',
 'image10052

In [13]:
import pandas as pd

# Create a DataFrame with image paths and predicted labels
df = pd.DataFrame({'Image_Path': img_path, 'Predicted_Labels': test_predicted_labels})

# Specify the path where you want to save the Excel file
excel_file_path = r'D:\PCOS_Challenge\pred_labels_of_test_images.xlsx'

# Save the DataFrame to an Excel file
df.to_excel(excel_file_path, index=False)
